# Generated by Django 5.2.5 on 2025-08-23 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('age', models.PositiveIntegerField()),
                ('patient_code', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient_code'], name='records_pat_patient_68bb47_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiaHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('age', models.FloatField()),
                ('pulse_rate', models.FloatField()),
                ('systolic_bp', models.FloatField()),
                ('diastolic_bp', models.FloatField()),
                ('glucose', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('family_diabetes', models.IntegerField()),
                ('hypertensive', models.IntegerField()),
                ('family_hypertension', models.IntegerField()),
                ('cvd', models.IntegerField()),
                ('stroke', models.IntegerField()),
                ('diabetic', models.IntegerField()),
                ('source', models.CharField(default='DiaHealth 2024', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['diabetic', 'age', 'bmi'], name='records_dia_diabeti_28a754_idx')],
            },
        ),
    ]
